<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Employee;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        function stringToDate($date){
            $date = \Carbon\Carbon::createFromFormat('d-m-Y', $date);
            return $date->toDateTimeString();
        }

        $employees = [
            [
                'nip' => '123456789012345001',
                'nama' => 'Saifulloh Rifai',
                'tp_lahir' => 'Banjarnegara',
                'alamat' => 'Jl. Melon No.16 Dian Asri',
                'tg_lahir' => stringToDate('5-03-1968'),
                'jenis_kl' => 'L',
                'gol' => 'IV/d',
                'eselon' => 'I',
                'jabatan' => 'Kepala Sekretariat Utama',
                'tp_tugas' => 'Jakarta',
                'agama' => 'Islam',
                'unit_kerja' => 'Kantor Pusat',
                'no_hp' => '089512345001',
                'npwp' => '1234567890123001',
            ],
            [
                'nip' => '123456789012345002',
                'nama' => 'Rudi Hartono',
                'tp_lahir' => 'Surabaya',
                'alamat' => 'Jl. Golf Komp Bakosurtanal No.39',
                'tg_lahir' => stringToDate('27-08-1968'),
                'jenis_kl' => 'L',
                'gol' => 'IV/a',
                'eselon' => 'II',
                'jabatan' => 'Penyusun laporan keuangan',
                'tp_tugas' => 'Bandung',
                'agama' => 'Islam',
                'unit_kerja' => 'Biro Keuangan',
                'no_hp' => '089512345002',
                'npwp' => '1234567890123002',
            ],
            [
                'nip' => '123456789012345003',
                'nama' => 'Fahmi Zulfikar',
                'tp_lahir' => 'Yogyakarta',
                'alamat' => 'Jl. Mendut III, Puri Nirwana I RT.03/16',
                'tg_lahir' => stringToDate('10-07-1987'),
                'jenis_kl' => 'L',
                'gol' => 'III/c',
                'eselon' => 'III',
                'jabatan' => 'Surveyor Pemetaan Pertama',
                'tp_tugas' => 'Bali',
                'agama' => 'Islam',
                'unit_kerja' => 'Kantor Survei',
                'no_hp' => '089512345003',
                'npwp' => '1234567890123003',
            ],
            [
                'nip' => '123456789012345004',
                'nama' => 'Siti Rahmawati',
                'tp_lahir' => 'Semarang',
                'alamat' => 'Perum Jombor Baru',
                'tg_lahir' => stringToDate('03-05-1987'),
                'jenis_kl' => 'P',
                'gol' => 'III/b',
                'eselon' => 'IV',
                'jabatan' => 'Analis Data Survei dan Pemetaan',
                'tp_tugas' => 'Solo',
                'agama' => 'Islam',
                'unit_kerja' => 'Biro Survei',
                'no_hp' => '089512345004',
                'npwp' => '1234567890123004',
            ],
            [
                'nip' => '123456789012345005',
                'nama' => 'Dani Hendra',
                'tp_lahir' => 'Trengalek',
                'alamat' => 'Trengalek',
                'tg_lahir' => stringToDate('07-07-1992'),
                'jenis_kl' => 'L',
                'gol' => 'III/a',
                'eselon' => 'V',
                'jabatan' => 'Perancang Per-UU-an Utama',
                'tp_tugas' => 'Medan',
                'agama' => 'Islam',
                'unit_kerja' => 'Biro Hukum',
                'no_hp' => '089512345005',
                'npwp' => '1234567890123005',
            ],
            [
                'nip' => '123456789012345006',
                'nama' => 'Hidayat Wira',
                'tp_lahir' => 'Bali',
                'alamat' => 'Bella Casa Residence Blok E.1 No.9',
                'tg_lahir' => stringToDate('05-06-1963'),
                'jenis_kl' => 'L',
                'gol' => 'IV/c',
                'eselon' => 'IV',
                'jabatan' => 'Kepala Biro Perencanaan, Kepegawaian dan',
                'tp_tugas' => 'Bandung',
                'agama' => 'Islam',
                'unit_kerja' => 'Biro Perencanaan',
                'no_hp' => '089512345006',
                'npwp' => '1234567890123006',
            ],
            [
                'nip' => '123456789012345007',
                'nama' => 'Aminah Putri',
                'tp_lahir' => 'Bogor',
                'alamat' => 'Jl. Pelita I/18 Kedung Halang Talang',
                'tg_lahir' => stringToDate('07-11-1952'),
                'jenis_kl' => 'P',
                'gol' => 'IV/d',
                'eselon' => 'V',
                'jabatan' => 'Widyaiswara Utama',
                'tp_tugas' => 'Jakarta',
                'agama' => 'Islam',
                'unit_kerja' => 'Biro Pendidikan',
                'no_hp' => '089512345007',
                'npwp' => '1234567890123007',
            ],
            [
                'nip' => '123456789012345008',
                'nama' => 'Agus Setiawan',
                'tp_lahir' => 'Surabaya',
                'alamat' => 'Komp. BAKOSURTANAL CIKARET',
                'tg_lahir' => stringToDate('12-09-1954'),
                'jenis_kl' => 'L',
                'gol' => 'IV/d',
                'eselon' => 'V',
                'jabatan' => 'Analis Kepegawaian',
                'tp_tugas' => 'Jakarta',
                'agama' => 'Islam',
                'unit_kerja' => 'Biro Kepegawaian',
                'no_hp' => '089512345008',
                'npwp' => '1234567890123008',
            ],
            [
                'nip' => '123456789012345009',
                'nama' => 'Rina Mariani',
                'tp_lahir' => 'Medan',
                'alamat' => 'Cigadung Selatan II/135',
                'tg_lahir' => stringToDate('30-11-1966'),
                'jenis_kl' => 'P',
                'gol' => 'IV/d',
                'eselon' => 'V',
                'jabatan' => 'Peneliti Pertama',
                'tp_tugas' => 'Bali',
                'agama' => 'Islam',
                'unit_kerja' => 'Biro Penelitian',
                'no_hp' => '089512345009',
                'npwp' => '1234567890123009',
            ],
            [
                'nip' => '123456789012345010',
                'nama' => 'Budi Santoso',
                'tp_lahir' => 'Palembang',
                'alamat' => 'Jl Raya Tegar Beriman Gg H Jairan No 116',
                'tg_lahir' => stringToDate('04-12-1962'),
                'jenis_kl' => 'L',
                'gol' => 'IV/c',
                'eselon' => 'V',
                'jabatan' => 'Analis Kepegawaian',
                'tp_tugas' => 'Bandung',
                'agama' => 'Islam',
                'unit_kerja' => 'Biro Kepegawaian',
                'no_hp' => '089512345010',
                'npwp' => '1234567890123010',
            ],
            [
                'nip' => '123456789012345011',
                'nama' => 'Eka Pratama',
                'tp_lahir' => 'Jakarta',
                'alamat' => 'Jl. Ciliwung RT.02/10',
                'tg_lahir' => stringToDate('03-07-1963'),
                'jenis_kl' => 'L',
                'gol' => 'III/c',
                'eselon' => 'III',
                'jabatan' => 'Surveyor Pemetaan Muda',
                'tp_tugas' => 'Jakarta',
                'agama' => 'Islam',
                'unit_kerja' => 'Kantor Survei',
                'no_hp' => '089512345011',
                'npwp' => '1234567890123011',
            ],
            [
                'nip' => '123456789012345012',
                'nama' => 'Lina Sari',
                'tp_lahir' => 'Jakarta',
                'alamat' => 'Jl.Kupu-kupu Blok NJ 16. RT.03/09',
                'tg_lahir' => stringToDate('22-08-1970'),
                'jenis_kl' => 'P',
                'gol' => 'III/c',
                'eselon' => 'III',
                'jabatan' => 'Surveyor Pemetaan Muda',
                'tp_tugas' => 'Bandung',
                'agama' => 'Islam',
                'unit_kerja' => 'Biro Survei',
                'no_hp' => '089512345012',
                'npwp' => '1234567890123012',
            ],
            [
                'nip' => '123456789012345013',
                'nama' => 'Anton Wijaya',
                'tp_lahir' => 'Surakarta',
                'alamat' => 'Kp. Sawah RT.01/11 No.27',
                'tg_lahir' => stringToDate('11-10-1958'),
                'jenis_kl' => 'L',
                'gol' => 'III/c',
                'eselon' => 'II',
                'jabatan' => 'Analis Jabatan',
                'tp_tugas' => 'Solo',
                'agama' => 'Islam',
                'unit_kerja' => 'Biro Jabatan',
                'no_hp' => '089512345013',
                'npwp' => '1234567890123013',
            ],
            [
                'nip' => '123456789012345014',
                'nama' => 'Rina Wulandari',
                'tp_lahir' => 'Jakarta',
                'alamat' => 'Jl. Kebon Pedes Gang Pacilong No. 4',
                'tg_lahir' => stringToDate('14-12-1967'),
                'jenis_kl' => 'P',
                'gol' => 'III/a',
                'eselon' => 'III',
                'jabatan' => 'Sekretaris Proyek',
                'tp_tugas' => 'Medan',
                'agama' => 'Islam',
                'unit_kerja' => 'Biro Keuangan',
                'no_hp' => '089512345014',
                'npwp' => '1234567890123014',
            ],
            [
                'nip' => '123456789012345015',
                'nama' => 'Mila Sari',
                'tp_lahir' => 'Surabaya',
                'alamat' => 'Jl Setasiun No 294 RT 06 RW 01',
                'tg_lahir' => stringToDate('09-04-1983'),
                'jenis_kl' => 'P',
                'gol' => 'IV/a',
                'eselon' => 'V',
                'jabatan' => 'Widyaiswara Pertama',
                'tp_tugas' => 'Bali',
                'agama' => 'Islam',
                'unit_kerja' => 'Biro Pendidikan',
                'no_hp' => '089512345015',
                'npwp' => '1234567890123015',
            ],
            [
                'nip' => '123456789012345016',
                'nama' => 'Hari Widodo',
                'tp_lahir' => 'Bandung',
                'alamat' => 'Perum Delivina Blok A.4/6',
                'tg_lahir' => stringToDate('04-08-1983'),
                'jenis_kl' => 'L',
                'gol' => 'II/a',
                'eselon' => 'V',
                'jabatan' => 'Administrasi Umum',
                'tp_tugas' => 'Bandung',
                'agama' => 'Islam',
                'unit_kerja' => 'Kantor Pusat',
                'no_hp' => '089512345016',
                'npwp' => '1234567890123016',
            ],
            [
                'nip' => '123456789012345017',
                'nama' => 'Umi Fatimah',
                'tp_lahir' => 'Surabaya',
                'alamat' => 'Jln.Golf Ling. 2 Citatah Dalam No.21',
                'tg_lahir' => stringToDate('14-08-1962'),
                'jenis_kl' => 'P',
                'gol' => 'III/c',
                'eselon' => 'V',
                'jabatan' => 'Teknisi Komputer',
                'tp_tugas' => 'Surabaya',
                'agama' => 'Islam',
                'unit_kerja' => 'Biro Teknologi',
                'no_hp' => '089512345017',
                'npwp' => '1234567890123017',
            ],
            [
                'nip' => '123456789012345018',
                'nama' => 'Dedi Surya',
                'tp_lahir' => 'Makassar',
                'alamat' => 'Jl. Ciliwung BCE RT.07/11',
                'tg_lahir' => stringToDate('21-02-1973'),
                'jenis_kl' => 'L',
                'gol' => 'IV/d',
                'eselon' => 'V',
                'jabatan' => 'Surveyor Pemetaan Utama',
                'tp_tugas' => 'Makassar',
                'agama' => 'Islam',
                'unit_kerja' => 'Kantor Survei',
                'no_hp' => '089512345018',
                'npwp' => '1234567890123018',
            ],
            [
                'nip' => '123456789012345019',
                'nama' => 'Rian Farhan',
                'tp_lahir' => 'Malang',
                'alamat' => 'Kp. Kandang',
                'tg_lahir' => stringToDate('29-04-1974'),
                'jenis_kl' => 'L',
                'gol' => 'II/b',
                'eselon' => 'V',
                'jabatan' => 'Asisten Analis',
                'tp_tugas' => 'Malang',
                'agama' => 'Islam',
                'unit_kerja' => 'Biro Analis',
                'no_hp' => '089512345019',
                'npwp' => '1234567890123019',
            ],
            [
                'nip' => '123456789012345020',
                'nama' => 'Siti Dwi',
                'tp_lahir' => 'Surakarta',
                'alamat' => 'Jl. Garuda Gg. Mangga RT002',
                'tg_lahir' => stringToDate('28-12-1975'),
                'jenis_kl' => 'P',
                'gol' => 'III/b',
                'eselon' => 'V',
                'jabatan' => 'Admin Umum',
                'tp_tugas' => 'Solo',
                'agama' => 'Islam',
                'unit_kerja' => 'Kantor Pusat',
                'no_hp' => '089512345020',
                'npwp' => '1234567890123020',
            ],
            [
                'nip' => '123456789012345021',
                'nama' => 'Rina Puspa',
                'tp_lahir' => 'Semarang',
                'alamat' => 'Perum Puri Karadenan Blok C 7',
                'tg_lahir' => stringToDate('26-03-1979'),
                'jenis_kl' => 'P',
                'gol' => 'III/b',
                'eselon' => 'V',
                'jabatan' => 'Admin Umum',
                'tp_tugas' => 'Semarang',
                'agama' => 'Islam',
                'unit_kerja' => 'Kantor Pusat',
                'no_hp' => '089512345021',
                'npwp' => '1234567890123021',
            ],
            [
                'nip' => '123456789012345022',
                'nama' => 'Lina Setiawati',
                'tp_lahir' => 'Yogyakarta',
                'alamat' => 'Jl. Satsiun No.225 RT.02/02',
                'tg_lahir' => stringToDate('12-06-1979'),
                'jenis_kl' => 'P',
                'gol' => 'III/b',
                'eselon' => 'V',
                'jabatan' => 'Admin Umum',
                'tp_tugas' => 'Yogyakarta',
                'agama' => 'Islam',
                'unit_kerja' => 'Kantor Pusat',
                'no_hp' => '089512345022',
                'npwp' => '1234567890123022',
            ],
            [
                'nip' => '123456789012345023',
                'nama' => 'Lina Wulandari',
                'tp_lahir' => 'Surabaya',
                'alamat' => 'Jl. Prambanan RT.12/16 Pabuaran',
                'tg_lahir' => stringToDate('11-01-1980'),
                'jenis_kl' => 'P',
                'gol' => 'III/b',
                'eselon' => 'V',
                'jabatan' => 'Admin Umum',
                'tp_tugas' => 'Surabaya',
                'agama' => 'Islam',
                'unit_kerja' => 'Kantor Pusat',
                'no_hp' => '089512345023',
                'npwp' => '1234567890123023',
            ],
            [
                'nip' => '123456789012345024',
                'nama' => 'Rika Pratiwi',
                'tp_lahir' => 'Bandung',
                'alamat' => 'Duta parahiyanganBlok AB 72',
                'tg_lahir' => stringToDate('07-02-1977'),
                'jenis_kl' => 'P',
                'gol' => 'III/b',
                'eselon' => 'V',
                'jabatan' => 'Admin Umum',
                'tp_tugas' => 'Bandung',
                'agama' => 'Islam',
                'unit_kerja' => 'Kantor Pusat',
                'no_hp' => '089512345024',
                'npwp' => '1234567890123024',
            ],
            [
                'nip' => '123456789012345025',
                'nama' => 'Mila Sari',
                'tp_lahir' => 'Jakarta',
                'alamat' => 'Jl Setasiun No 294 RT 06 RW 01',
                'tg_lahir' => stringToDate('06-03-1980'),
                'jenis_kl' => 'P',
                'gol' => 'III/b',
                'eselon' => 'V',
                'jabatan' => 'Admin Umum',
                'tp_tugas' => 'Jakarta',
                'agama' => 'Islam',
                'unit_kerja' => 'Kantor Pusat',
                'no_hp' => '089512345025',
                'npwp' => '1234567890123025',
            ],
        ];

        foreach ($employees as $employee) {
            Employee::query()->create($employee);
        }
    }
}
